# Generated by Django 5.2.1 on 2026-03-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_family_loksabha_family_sambhag'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='gotra_image',
            field=models.ImageField(blank=True, null=True, upload_to='gotra_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='height',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['gender'], name='members_mem_gender_b3393e_idx'),
        ),
    ]
