# Generated by Django 5.2.1 on 2026-03-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
