# Generated by Django 5.0.14 on 2026-03-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0005_remove_family_families_fa_name_9f3d76_idx_and_more'),
        ('members', '0005_member_blood_group_member_degree_diploma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_active'], name='members_mem_is_acti_65d5c9_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['is_deleted'], name='members_mem_is_dele_e5d6f3_idx'),
        ),
    ]
