# Generated by Django 5.0.14 on 2026-03-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_created_at_member_is_active_member_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Married'), ('unmarried', 'Unmarried'), ('widow', 'Widow'), ('widower', 'Widower'), ('divorced', 'Divorced')], max_length=50, null=True),
        ),
    ]
