# Generated by Django 5.0.14 on 2026-03-24 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_family_community'),
        ('locations', '0002_alter_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='loksabha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_loksabhas', to='locations.location'),
        ),
        migrations.AddField(
            model_name='family',
            name='sambhag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_sambhags', to='locations.location'),
        ),
    ]
