# Generated by Django 5.0.14 on 2026-03-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_family_loksabha_family_sambhag'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
