# Generated by Django 5.0.14 on 2026-03-28 05:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
        ('families', '0004_family_pincode'),
        ('locations', '0002_alter_location_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='family',
            name='families_fa_name_9f3d76_idx',
        ),
        migrations.AddField(
            model_name='family',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_active'], name='families_fa_is_acti_993bdd_idx'),
        ),
    ]
