# Generated by Django 5.0.14 on 2026-03-20 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('state', 'State'), ('district', 'District'), ('zone', 'Zone'), ('vidhansabha', 'Vidhansabha'), ('ward', 'Ward')], max_length=20)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='community.community')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.location')),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='locations_l_type_836019_idx'), models.Index(fields=['parent'], name='locations_l_parent__2d4346_idx')],
            },
        ),
    ]
