# Generated by Django 5.0.14 on 2026-03-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.CharField(choices=[('state', 'State'), ('sambhag', 'Sambhag'), ('loksabha', 'Loksabha'), ('district', 'District'), ('zone', 'Zone'), ('vidhansabha', 'Vidhansabha'), ('ward', 'Ward')], max_length=20),
        ),
    ]
